apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-ac6s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componenta-devfile-sample-go-basic-private-devfile-nested-ac6s
    app.kubernetes.io/part-of: mc-golang-nested
  name: componenta-devfile-sample-go-basic-private-devfile-nested-ac6s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-ac6s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-ac6s
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lesz-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-ac6s@sha256:425f5b85cca7055d32aa0df41824a3a15536c3d16c7fb0a1389ff5f546eb1b8a
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 12m
            memory: 18Mi
status: {}
